QT.sql_private.VERSION = 5.6.1
QT.sql_private.MAJOR_VERSION = 5
QT.sql_private.MINOR_VERSION = 6
QT.sql_private.PATCH_VERSION = 1
QT.sql_private.name = QtSql
QT.sql_private.module =
QT.sql_private.libs = $$QT_MODULE_LIB_BASE
QT.sql_private.includes = $$QT_MODULE_INCLUDE_BASE/QtSql/5.6.1 $$QT_MODULE_INCLUDE_BASE/QtSql/5.6.1/QtSql
QT.sql_private.frameworks =
QT.sql_private.depends = core_private sql
QT.sql_private.module_config = v2 internal_module
