QT.nfc_private.VERSION = 5.6.1
QT.nfc_private.MAJOR_VERSION = 5
QT.nfc_private.MINOR_VERSION = 6
QT.nfc_private.PATCH_VERSION = 1
QT.nfc_private.name = QtNfc
QT.nfc_private.module =
QT.nfc_private.libs = $$QT_MODULE_LIB_BASE
QT.nfc_private.includes = $$QT_MODULE_INCLUDE_BASE/QtNfc/5.6.1 $$QT_MODULE_INCLUDE_BASE/QtNfc/5.6.1/QtNfc
QT.nfc_private.frameworks =
QT.nfc_private.depends = nfc
QT.nfc_private.module_config = v2 internal_module
