QT.gui_private.VERSION = 5.6.1
QT.gui_private.MAJOR_VERSION = 5
QT.gui_private.MINOR_VERSION = 6
QT.gui_private.PATCH_VERSION = 1
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.6.1 $$QT_MODULE_INCLUDE_BASE/QtGui/5.6.1/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.module_config = v2 internal_module
