/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "5.6.1"

#define QTUIPLUGIN_VERSION 0x050601

#endif // QT_QTUIPLUGIN_VERSION_H
